# Generated by Django 3.2.9 on 2021-12-05 19:04

import birthday.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=birthday.fields.BirthdayField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday_dayofyear_internal',
            field=models.PositiveSmallIntegerField(default=None, editable=False, null=True),
        ),
    ]
